name: Lint

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2-beta
      with:
        node-version: 20

    - run: npm ci
    - run: npm rum lint
    - run: npm run build
